export interface Cell {
  alive: boolean;
}

export const DEAD = false;
export const LIVE = true;

export const DEAD_CELL: Cell = {alive: DEAD};
export const LIVE_CELL: Cell = {alive: LIVE};

export const TOAD: Cell[][] = [
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, LIVE_CELL,  LIVE_CELL,  LIVE_CELL,  DEAD_CELL],
  [ DEAD_CELL,  LIVE_CELL, LIVE_CELL,  LIVE_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL,  DEAD_CELL]
];

export const BLNKER: Cell[][] = [
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, LIVE_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, LIVE_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, LIVE_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL]
];

export const BEACON: Cell[][] = [
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  LIVE_CELL, LIVE_CELL,  DEAD_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  LIVE_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  LIVE_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  LIVE_CELL,  LIVE_CELL,  DEAD_CELL],
  [ DEAD_CELL,  DEAD_CELL, DEAD_CELL,  DEAD_CELL,  DEAD_CELL,  DEAD_CELL]
];
